# LinkedIn Deep Learning Thought Leadership Agent Credentials
# IMPORTANT: This is an example file. Copy to credentials.yml and fill with your actual credentials.
# DO NOT commit credentials.yml to version control!

# LinkedIn API credentials
linkedin:
  client_id: YOUR_LINKEDIN_CLIENT_ID
  client_secret: YOUR_LINKEDIN_CLIENT_SECRET
  redirect_uri: http://localhost:8000/callback
  access_token: YOUR_LINKEDIN_ACCESS_TOKEN
  refresh_token: YOUR_LINKEDIN_REFRESH_TOKEN

# OpenAI API credentials (for content generation)
openai:
  api_key: YOUR_OPENAI_API_KEY

# Alternative LLM providers
anthropic:
  api_key: YOUR_ANTHROPIC_API_KEY

huggingface:
  api_key: YOUR_HUGGINGFACE_API_KEY

# Database credentials
mongodb:
  username: YOUR_MONGODB_USERNAME
  password: YOUR_MONGODB_PASSWORD
  host: localhost
  port: 27017
  database: linkedin_agent

influxdb:
  username: YOUR_INFLUXDB_USERNAME
  password: YOUR_INFLUXDB_PASSWORD
  host: localhost
  port: 8086
  database: linkedin_metrics

# Email notifications (for approval workflow)
email:
  smtp_server: smtp.example.com
  smtp_port: 587
  username: rjabbala@gmail.com
  password: Arunachala@1950
  from_address: noreply@example.com
  to_address: rjabbala@gmail.com 
